name: flutter_modular

sdkPath: .fvm/flutter_sdk

packages:
  - app/**
  - core/**

command:
  bootstrap:
    usePubspecOverrides: true
scripts:
  analyze:
    exec: dart analyze .
  env:
    exec:
      concurrency: 6
      failFast: true
    run: flutter pub run build_runner clean && flutter pub run build_runner build --delete-conflicting-outputs
    description: Run a build_runner build in the ODM example app.
    packageFilters:
      dependsOn: "envied_generator"
  clean:app:
    exec:
      concurrency: 6
      failFast: false
    run: flutter clean
    description: Clean project
    packageFilters:
      fileExists:
        - "lib/main.dart"
  build_apk_release:
    exec:
      concurrency: 6
      failFast: false
    run: flutter build apk --release
    description: Run a build APK Release.
    packageFilters:
      fileExists:
        - "lib/main.dart"
  build_apk_dev:
    exec:
      concurrency: 6
      failFast: false
    run: flutter build apk --debug --split-debug-info=build/flutter_mapping
    description: Run a build APK Release.
    packageFilters:
      fileExists:
        - "lib/main.dart"
  build_web_release:
    exec:
      concurrency: 6
      failFast: false
    run: flutter build apk --release --obfuscate --split-debug-info=build/flutter_mapping
    description: Run a build APK Release.
    packageFilters:
      fileExists:
        - "lib/main.dart"